version: '3'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: myparcelcom/sdk-php:v3-dev
    working_dir: /opt/sdk
    volumes:
      - .:/opt/sdk
      - composercache:/root/.composer/cache

  php73:
    build:
      context: ./docker/php73
      dockerfile: Dockerfile
    image: myparcelcom/sdk-php73:v1-dev
    working_dir: /opt/sdk
    volumes:
      - .:/opt/sdk
      - composercache:/root/.composer/cache

volumes:
  composercache:
    driver: local
