services:
  php8:
    build:
      context: ./docker/php8
      dockerfile: Dockerfile
    image: myparcelcom/sdk-php8:v2-dev
    working_dir: /opt/sdk
    volumes:
      - .:/opt/sdk
      - ./docker/php8/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - composercache:/root/.composer/cache

volumes:
  composercache:
    driver: local
