version: '3'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: myparcelcom/sdk-php:v1-dev
    working_dir: /opt/sdk
    volumes:
      - .:/opt/sdk
      - composercache:/.composer/cache

volumes:
  composercache:
    driver: local
