version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Run tests on PHP 5.6
          command: |
            ./mp.sh php5 composer update
            ./mp.sh php5 test --no-coverage --stop-on-failure
      - run:
          name: Run tests on PHP 7.4
          command: |
            ./mp.sh php7 composer update
            ./mp.sh php7 test --no-coverage --stop-on-failure
