version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge

    steps:
      - checkout

      - run:
          name: Setup dependencies
          command: |
            ./mp.sh composer install

      - run:
          name: Run tests on default PHP version (5.6)
          command: |
            ./mp.sh test --no-coverage --stop-on-failure

      - run:
          name: Run tests on PHP 7.0
          command: |
            ./mp.sh test --no-coverage --stop-on-failure

      - run:
          name: Run tests on PHP 7.1
          command: |
            ./mp.sh test --no-coverage --stop-on-failure

      - run:
          name: Run tests on PHP 7.2 with symfony/cache ^5.0
          command: |
            ./mp.sh composer require symfony/cache:^5.0
            ./mp.sh test --no-coverage --stop-on-failure
