version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Run tests on PHP 5.6
          command: |
            ./mp.sh composer update
            ./mp.sh test --no-coverage --stop-on-failure
      - run:
          name: Run tests on PHP 7.3
          command: |
            ./mp.sh php73 composer update
            ./mp.sh php73 test --no-coverage --stop-on-failure
