name: Tests
on: push
jobs:
  php80:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          version: 9
          php_version: 8.0
          configuration: phpunit.xml
  php81:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.1
      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          version: 9
          php_version: 8.1
          configuration: phpunit.xml
  php82:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: 8.2
      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          version: 9
          php_version: 8.2
          configuration: phpunit.xml
